### ISSUE TITLE
Cards need to be more flexible

### ISSUE THREAD

**Issue by daveaccent** [AccentDesign/karma-css#11]
Cards currently impose too much design by default to be reused and built upon cleanly. Would like to see options like header, footer which would make the card more flexible.

**Comment by stuartaccent** [comment]
Agreed, there only there because they are on the home page. The plan is at some point to replace with others, but i think there is a need to maybe create a basic set of components in a separate package that can be built upon. Im not sure where we want to take components going forward, they were only ever examples to show you dont need a complete framework to create them when you only ever use very few of them.

Thoughts @daveaccent.

**Comment by daveaccent** [comment]
Good point, as we build these components it would be nice to add them to Karma.

**Comment by stuartaccent** [comment]
closing this for now till we expand on components, cards have been removed from docs
